[
  {
    "file": "src/server.ts",
    "modifications": [
      {
        "old_str": "// Receive payment for receivable\n  app.post(\"/api/receivables/:id/payment\", async (req, res) => {\n    try {\n      const { id } = req.params;\n      const { amount, method, transactionId, notes } = req.body;\n\n      console.log(`Registering payment for receivable: ${id}`, { amount, method });\n\n      if (!amount || isNaN(parseFloat(amount)) || parseFloat(amount) <= 0) {\n        return res.status(400).json({ error: \"Valor deve ser maior que zero\" });\n      }\n\n      // Check if this is a manual receivable\n      if (id.startsWith('manual-')) {\n        const manualReceivables = await storage.getManualReceivables();\n        const receivable = manualReceivables.find((r: any) => r.id === id);\n\n        if (!receivable) {\n          return res.status(404).json({ error: \"Conta a receber não encontrada\" });\n        }\n\n        const currentReceived = parseFloat(receivable.receivedAmount || \"0\");\n        const paymentAmount = parseFloat(amount);\n        const newReceivedAmount = (currentReceived + paymentAmount).toFixed(2);\n\n        // Update the manual receivable\n        await storage.updateAccountsReceivable(id, {\n          receivedAmount: newReceivedAmount\n        });\n\n        console.log(`Manual receivable payment registered: ${id}, amount: ${amount}`);\n\n        res.json({\n          success: true,\n          receivable: {\n            ...receivable,\n            receivedAmount: newReceivedAmount\n          }\n        });\n        return;\n      }\n\n      // Handle order-based receivables\n      const receivables = await storage.getAccountsReceivable();\n      const receivable = receivables.find((r: any) => r.id === id);\n\n      if (!receivable) {\n        return res.status(404).json({ error: \"Conta a receber não encontrada\" });\n      }\n\n      if (!receivable.orderId) {\n        return res.status(400).json({ error: \"Esta conta a receber não está associada a um pedido\" });\n      }\n\n      // Create payment record for the order\n      const payment = await storage.createPayment({\n        orderId: receivable.orderId,\n        amount: parseFloat(amount).toFixed(2),\n        method: method || \"manual\",\n        status: \"confirmed\",\n        transactionId: transactionId || `MANUAL-${Date.now()}`,\n        paidAt: new Date()\n      });\n\n      console.log(`Payment registered successfully for receivable ${id}:`, payment.id);\n\n      res.json({\n        success: true,\n        payment: payment,\n        message: \"Pagamento registrado com sucesso\"\n      });\n\n    } catch (error) {\n      console.error(\"Error registering receivable payment:\", error);\n      res.status(500).json({ error: \"Erro ao registrar pagamento: \" + error.message });\n    }\n  });",
        "new_str": "// Receive payment for receivable\n  app.post(\"/api/receivables/:id/payment\", async (req, res) => {\n    try {\n      const { id } = req.params;\n      const { amount, method, transactionId, notes } = req.body;\n\n      console.log(`Registering payment for receivable: ${id}`, { amount, method, transactionId, notes });\n\n      if (!amount || isNaN(parseFloat(amount)) || parseFloat(amount) <= 0) {\n        return res.status(400).json({ error: \"Valor deve ser maior que zero\" });\n      }\n\n      // Check if this is a manual receivable\n      if (id.startsWith('manual-')) {\n        const manualReceivables = await storage.getManualReceivables();\n        const receivable = manualReceivables.find((r: any) => r.id === id);\n\n        if (!receivable) {\n          return res.status(404).json({ error: \"Conta a receber não encontrada\" });\n        }\n\n        const currentReceived = parseFloat(receivable.receivedAmount || \"0\");\n        const paymentAmount = parseFloat(amount);\n        const newReceivedAmount = (currentReceived + paymentAmount).toFixed(2);\n\n        // Update the manual receivable\n        await storage.updateAccountsReceivable(id, {\n          receivedAmount: newReceivedAmount\n        });\n\n        console.log(`Manual receivable payment registered: ${id}, amount: ${amount}`);\n\n        return res.json({\n          success: true,\n          receivable: {\n            ...receivable,\n            receivedAmount: newReceivedAmount\n          }\n        });\n      }\n\n      // Handle order-based receivables\n      const receivables = await storage.getAccountsReceivable();\n      const receivable = receivables.find((r: any) => r.id === id);\n\n      if (!receivable) {\n        return res.status(404).json({ error: \"Conta a receber não encontrada\" });\n      }\n\n      if (!receivable.orderId) {\n        return res.status(400).json({ error: \"Esta conta a receber não está associada a um pedido\" });\n      }\n\n      // Create payment record for the order\n      const payment = await storage.createPayment({\n        orderId: receivable.orderId,\n        amount: parseFloat(amount).toFixed(2),\n        method: method || \"manual\",\n        status: \"confirmed\",\n        transactionId: transactionId || `MANUAL-${Date.now()}`,\n        notes: notes || \"\",\n        paidAt: new Date()\n      });\n\n      console.log(`Payment registered successfully for receivable ${id}:`, payment.id);\n\n      return res.json({\n        success: true,\n        payment: payment,\n        message: \"Pagamento registrado com sucesso\"\n      });\n\n    } catch (error) {\n      console.error(\"Error registering receivable payment:\", error);\n      return res.status(500).json({ error: \"Erro ao registrar pagamento: \" + error.message });\n    }\n  });"
      }
    ]
  }
]
```